apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ include "example-go-web-service.fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "example-go-web-service.fullname" . }}
              servicePort: {{ .Values.service.port }}
    - host: example.com
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "example-go-web-service.fullname" . }}
              servicePort: {{ .Values.service.port }}
    - host: {{ include "example-go-web-service.fullname" . }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "example-go-web-service.fullname" . }}
              servicePort: {{ .Values.service.port }}
    - host: {{ include "example-go-web-service.fullname" . }}.default
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "example-go-web-service.fullname" . }}
              servicePort: {{ .Values.service.port }}
    - host: {{ include "example-go-web-service.fullname" . }}.default.svc.cluster.local
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ include "example-go-web-service.fullname" . }}
              servicePort: {{ .Values.service.port }}
